// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConditionClient is the client API for Condition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConditionClient interface {
	ConditionStatus(ctx context.Context, in *JobConditionReq, opts ...grpc.CallOption) (*JobConditionRes, error)
}

type conditionClient struct {
	cc grpc.ClientConnInterface
}

func NewConditionClient(cc grpc.ClientConnInterface) ConditionClient {
	return &conditionClient{cc}
}

func (c *conditionClient) ConditionStatus(ctx context.Context, in *JobConditionReq, opts ...grpc.CallOption) (*JobConditionRes, error) {
	out := new(JobConditionRes)
	err := c.cc.Invoke(ctx, "/data.Condition/ConditionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConditionServer is the server API for Condition service.
// All implementations must embed UnimplementedConditionServer
// for forward compatibility
type ConditionServer interface {
	ConditionStatus(context.Context, *JobConditionReq) (*JobConditionRes, error)
	mustEmbedUnimplementedConditionServer()
}

// UnimplementedConditionServer must be embedded to have forward compatible implementations.
type UnimplementedConditionServer struct {
}

func (UnimplementedConditionServer) ConditionStatus(context.Context, *JobConditionReq) (*JobConditionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConditionStatus not implemented")
}
func (UnimplementedConditionServer) mustEmbedUnimplementedConditionServer() {}

// UnsafeConditionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConditionServer will
// result in compilation errors.
type UnsafeConditionServer interface {
	mustEmbedUnimplementedConditionServer()
}

func RegisterConditionServer(s grpc.ServiceRegistrar, srv ConditionServer) {
	s.RegisterService(&Condition_ServiceDesc, srv)
}

func _Condition_ConditionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobConditionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConditionServer).ConditionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Condition/ConditionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConditionServer).ConditionStatus(ctx, req.(*JobConditionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Condition_ServiceDesc is the grpc.ServiceDesc for Condition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Condition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Condition",
	HandlerType: (*ConditionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConditionStatus",
			Handler:    _Condition_ConditionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "condition.proto",
}
