// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: exit_code.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExitCode int32

const (
	ExitCode_SUCCESS ExitCode = 0
	ExitCode_FAILED  ExitCode = 1
	ExitCode_ABORTED ExitCode = 2
)

// Enum value maps for ExitCode.
var (
	ExitCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "ABORTED",
	}
	ExitCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
		"ABORTED": 2,
	}
)

func (x ExitCode) Enum() *ExitCode {
	p := new(ExitCode)
	*p = x
	return p
}

func (x ExitCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExitCode) Descriptor() protoreflect.EnumDescriptor {
	return file_exit_code_proto_enumTypes[0].Descriptor()
}

func (ExitCode) Type() protoreflect.EnumType {
	return &file_exit_code_proto_enumTypes[0]
}

func (x ExitCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExitCode.Descriptor instead.
func (ExitCode) EnumDescriptor() ([]byte, []int) {
	return file_exit_code_proto_rawDescGZIP(), []int{0}
}

// Request message to update the run status of job
type RunStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string   `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	Status  ExitCode `protobuf:"varint,2,opt,name=Status,proto3,enum=data.ExitCode" json:"Status,omitempty"`
}

func (x *RunStatusReq) Reset() {
	*x = RunStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_code_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatusReq) ProtoMessage() {}

func (x *RunStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_exit_code_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatusReq.ProtoReflect.Descriptor instead.
func (*RunStatusReq) Descriptor() ([]byte, []int) {
	return file_exit_code_proto_rawDescGZIP(), []int{0}
}

func (x *RunStatusReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RunStatusReq) GetStatus() ExitCode {
	if x != nil {
		return x.Status
	}
	return ExitCode_SUCCESS
}

// Response message for job's run status update
type RunStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunStatusRes) Reset() {
	*x = RunStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_code_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatusRes) ProtoMessage() {}

func (x *RunStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_exit_code_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatusRes.ProtoReflect.Descriptor instead.
func (*RunStatusRes) Descriptor() ([]byte, []int) {
	return file_exit_code_proto_rawDescGZIP(), []int{1}
}

var File_exit_code_proto protoreflect.FileDescriptor

var file_exit_code_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x75, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x2a, 0x30, 0x0a, 0x08, 0x45, 0x78, 0x69,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0x3f, 0x0a, 0x09, 0x52,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x75,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exit_code_proto_rawDescOnce sync.Once
	file_exit_code_proto_rawDescData = file_exit_code_proto_rawDesc
)

func file_exit_code_proto_rawDescGZIP() []byte {
	file_exit_code_proto_rawDescOnce.Do(func() {
		file_exit_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_exit_code_proto_rawDescData)
	})
	return file_exit_code_proto_rawDescData
}

var file_exit_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exit_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exit_code_proto_goTypes = []interface{}{
	(ExitCode)(0),        // 0: data.ExitCode
	(*RunStatusReq)(nil), // 1: data.RunStatusReq
	(*RunStatusRes)(nil), // 2: data.RunStatusRes
}
var file_exit_code_proto_depIdxs = []int32{
	0, // 0: data.RunStatusReq.Status:type_name -> data.ExitCode
	1, // 1: data.RunStatus.Update:input_type -> data.RunStatusReq
	2, // 2: data.RunStatus.Update:output_type -> data.RunStatusRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exit_code_proto_init() }
func file_exit_code_proto_init() {
	if File_exit_code_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exit_code_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exit_code_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exit_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exit_code_proto_goTypes,
		DependencyIndexes: file_exit_code_proto_depIdxs,
		EnumInfos:         file_exit_code_proto_enumTypes,
		MessageInfos:      file_exit_code_proto_msgTypes,
	}.Build()
	File_exit_code_proto = out.File
	file_exit_code_proto_rawDesc = nil
	file_exit_code_proto_goTypes = nil
	file_exit_code_proto_depIdxs = nil
}
