// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PickJobsClient is the client API for PickJobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PickJobsClient interface {
	Pick(ctx context.Context, in *PickJobsReq, opts ...grpc.CallOption) (*PickJobsRes, error)
}

type pickJobsClient struct {
	cc grpc.ClientConnInterface
}

func NewPickJobsClient(cc grpc.ClientConnInterface) PickJobsClient {
	return &pickJobsClient{cc}
}

func (c *pickJobsClient) Pick(ctx context.Context, in *PickJobsReq, opts ...grpc.CallOption) (*PickJobsRes, error) {
	out := new(PickJobsRes)
	err := c.cc.Invoke(ctx, "/data.PickJobs/Pick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PickJobsServer is the server API for PickJobs service.
// All implementations must embed UnimplementedPickJobsServer
// for forward compatibility
type PickJobsServer interface {
	Pick(context.Context, *PickJobsReq) (*PickJobsRes, error)
	mustEmbedUnimplementedPickJobsServer()
}

// UnimplementedPickJobsServer must be embedded to have forward compatible implementations.
type UnimplementedPickJobsServer struct {
}

func (UnimplementedPickJobsServer) Pick(context.Context, *PickJobsReq) (*PickJobsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pick not implemented")
}
func (UnimplementedPickJobsServer) mustEmbedUnimplementedPickJobsServer() {}

// UnsafePickJobsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PickJobsServer will
// result in compilation errors.
type UnsafePickJobsServer interface {
	mustEmbedUnimplementedPickJobsServer()
}

func RegisterPickJobsServer(s grpc.ServiceRegistrar, srv PickJobsServer) {
	s.RegisterService(&PickJobs_ServiceDesc, srv)
}

func _PickJobs_Pick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickJobsServer).Pick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.PickJobs/Pick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickJobsServer).Pick(ctx, req.(*PickJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PickJobs_ServiceDesc is the grpc.ServiceDesc for PickJobs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PickJobs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.PickJobs",
	HandlerType: (*PickJobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pick",
			Handler:    _PickJobs_Pick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "next.proto",
}
