// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: run.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type to represent job status
type Status int32

const (
	Status_IDLE    Status = 0
	Status_QUEUED  Status = 1
	Status_READY   Status = 2
	Status_RUNNING Status = 3
	Status_SUCCESS Status = 4
	Status_FAILED  Status = 5
	Status_ABORTED Status = 6
	Status_FROZEN  Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "IDLE",
		1: "QUEUED",
		2: "READY",
		3: "RUNNING",
		4: "SUCCESS",
		5: "FAILED",
		6: "ABORTED",
		7: "FROZEN",
	}
	Status_value = map[string]int32{
		"IDLE":    0,
		"QUEUED":  1,
		"READY":   2,
		"RUNNING": 3,
		"SUCCESS": 4,
		"FAILED":  5,
		"ABORTED": 6,
		"FROZEN":  7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_run_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_run_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

// Request message to get run status of job
type GetJobRunStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *GetJobRunStatusReq) Reset() {
	*x = GetJobRunStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRunStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRunStatusReq) ProtoMessage() {}

func (x *GetJobRunStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRunStatusReq.ProtoReflect.Descriptor instead.
func (*GetJobRunStatusReq) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobRunStatusReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// Response message for job run status
type GetJobRunStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName    string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	StartTime  string `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime    string `protobuf:"bytes,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	StatusType Status `protobuf:"varint,4,opt,name=StatusType,proto3,enum=data.Status" json:"StatusType,omitempty"`
}

func (x *GetJobRunStatusRes) Reset() {
	*x = GetJobRunStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRunStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRunStatusRes) ProtoMessage() {}

func (x *GetJobRunStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRunStatusRes.ProtoReflect.Descriptor instead.
func (*GetJobRunStatusRes) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobRunStatusRes) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *GetJobRunStatusRes) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetJobRunStatusRes) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetJobRunStatusRes) GetStatusType() Status {
	if x != nil {
		return x.StatusType
	}
	return Status_IDLE
}

// Request message to get run history of job
type GetJobRunHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *GetJobRunHistoryReq) Reset() {
	*x = GetJobRunHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRunHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRunHistoryReq) ProtoMessage() {}

func (x *GetJobRunHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRunHistoryReq.ProtoReflect.Descriptor instead.
func (*GetJobRunHistoryReq) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRunHistoryReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// Response message for job run history
type GetJobRunHistoryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName    string   `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	StartTime  []string `protobuf:"bytes,2,rep,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime    []string `protobuf:"bytes,3,rep,name=EndTime,proto3" json:"EndTime,omitempty"`
	StatusType []Status `protobuf:"varint,4,rep,packed,name=StatusType,proto3,enum=data.Status" json:"StatusType,omitempty"`
}

func (x *GetJobRunHistoryRes) Reset() {
	*x = GetJobRunHistoryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRunHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRunHistoryRes) ProtoMessage() {}

func (x *GetJobRunHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRunHistoryRes.ProtoReflect.Descriptor instead.
func (*GetJobRunHistoryRes) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobRunHistoryRes) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *GetJobRunHistoryRes) GetStartTime() []string {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetJobRunHistoryRes) GetEndTime() []string {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetJobRunHistoryRes) GetStatusType() []Status {
	if x != nil {
		return x.StatusType
	}
	return nil
}

// Request message to get jil
type GetJilReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *GetJilReq) Reset() {
	*x = GetJilReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJilReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJilReq) ProtoMessage() {}

func (x *GetJilReq) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJilReq.ProtoReflect.Descriptor instead.
func (*GetJilReq) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{4}
}

func (x *GetJilReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// Response message of jil
type GetJilRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName    string   `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	Command    string   `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	Conditions []string `protobuf:"bytes,3,rep,name=Conditions,proto3" json:"Conditions,omitempty"`
	StdOut     string   `protobuf:"bytes,4,opt,name=StdOut,proto3" json:"StdOut,omitempty"`
	StdErr     string   `protobuf:"bytes,5,opt,name=StdErr,proto3" json:"StdErr,omitempty"`
	Machine    string   `protobuf:"bytes,6,opt,name=Machine,proto3" json:"Machine,omitempty"`
	RunDays    string   `protobuf:"bytes,7,opt,name=RunDays,proto3" json:"RunDays,omitempty"`
	StartTimes string   `protobuf:"bytes,8,opt,name=StartTimes,proto3" json:"StartTimes,omitempty"`
}

func (x *GetJilRes) Reset() {
	*x = GetJilRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJilRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJilRes) ProtoMessage() {}

func (x *GetJilRes) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJilRes.ProtoReflect.Descriptor instead.
func (*GetJilRes) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{5}
}

func (x *GetJilRes) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *GetJilRes) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetJilRes) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *GetJilRes) GetStdOut() string {
	if x != nil {
		return x.StdOut
	}
	return ""
}

func (x *GetJilRes) GetStdErr() string {
	if x != nil {
		return x.StdErr
	}
	return ""
}

func (x *GetJilRes) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *GetJilRes) GetRunDays() string {
	if x != nil {
		return x.RunDays
	}
	return ""
}

func (x *GetJilRes) GetStartTimes() string {
	if x != nil {
		return x.StartTimes
	}
	return ""
}

var File_run_proto protoreflect.FileDescriptor

var file_run_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x25, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xe3, 0x01, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x4a, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x64, 0x4f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x64, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x45, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x64, 0x45, 0x72, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x2a, 0x68,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x52, 0x4f, 0x5a, 0x45, 0x4e, 0x10, 0x07, 0x32, 0xd8, 0x01, 0x0a, 0x09, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x47, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62,
	0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x4a, 0x6f, 0x62, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_run_proto_rawDescOnce sync.Once
	file_run_proto_rawDescData = file_run_proto_rawDesc
)

func file_run_proto_rawDescGZIP() []byte {
	file_run_proto_rawDescOnce.Do(func() {
		file_run_proto_rawDescData = protoimpl.X.CompressGZIP(file_run_proto_rawDescData)
	})
	return file_run_proto_rawDescData
}

var file_run_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_run_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_run_proto_goTypes = []interface{}{
	(Status)(0),                 // 0: data.Status
	(*GetJobRunStatusReq)(nil),  // 1: data.GetJobRunStatusReq
	(*GetJobRunStatusRes)(nil),  // 2: data.GetJobRunStatusRes
	(*GetJobRunHistoryReq)(nil), // 3: data.GetJobRunHistoryReq
	(*GetJobRunHistoryRes)(nil), // 4: data.GetJobRunHistoryRes
	(*GetJilReq)(nil),           // 5: data.GetJilReq
	(*GetJilRes)(nil),           // 6: data.GetJilRes
}
var file_run_proto_depIdxs = []int32{
	0, // 0: data.GetJobRunStatusRes.StatusType:type_name -> data.Status
	0, // 1: data.GetJobRunHistoryRes.StatusType:type_name -> data.Status
	1, // 2: data.JobStatus.GetJobRunStatus:input_type -> data.GetJobRunStatusReq
	3, // 3: data.JobStatus.GetJobRunHistory:input_type -> data.GetJobRunHistoryReq
	5, // 4: data.JobStatus.GetJobDefinition:input_type -> data.GetJilReq
	2, // 5: data.JobStatus.GetJobRunStatus:output_type -> data.GetJobRunStatusRes
	4, // 6: data.JobStatus.GetJobRunHistory:output_type -> data.GetJobRunHistoryRes
	6, // 7: data.JobStatus.GetJobDefinition:output_type -> data.GetJilRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_run_proto_init() }
func file_run_proto_init() {
	if File_run_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_run_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRunStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRunStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRunHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRunHistoryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJilReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJilRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_run_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_run_proto_goTypes,
		DependencyIndexes: file_run_proto_depIdxs,
		EnumInfos:         file_run_proto_enumTypes,
		MessageInfos:      file_run_proto_msgTypes,
	}.Build()
	File_run_proto = out.File
	file_run_proto_rawDesc = nil
	file_run_proto_goTypes = nil
	file_run_proto_depIdxs = nil
}
