// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: jil.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type to represent JIL action
type JilAction int32

const (
	JilAction_INSERT JilAction = 0
	JilAction_UPDATE JilAction = 1
	JilAction_DELETE JilAction = 2
)

// Enum value maps for JilAction.
var (
	JilAction_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "DELETE",
	}
	JilAction_value = map[string]int32{
		"INSERT": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x JilAction) Enum() *JilAction {
	p := new(JilAction)
	*p = x
	return p
}

func (x JilAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JilAction) Descriptor() protoreflect.EnumDescriptor {
	return file_jil_proto_enumTypes[0].Descriptor()
}

func (JilAction) Type() protoreflect.EnumType {
	return &file_jil_proto_enumTypes[0]
}

func (x JilAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JilAction.Descriptor instead.
func (JilAction) EnumDescriptor() ([]byte, []int) {
	return file_jil_proto_rawDescGZIP(), []int{0}
}

// Message to represent JIL data for job
type JilData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName       string   `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	JobType       string   `protobuf:"bytes,2,opt,name=JobType,proto3" json:"JobType,omitempty"`
	BoxName       string   `protobuf:"bytes,3,opt,name=BoxName,proto3" json:"BoxName,omitempty"`
	Command       string   `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	Conditions    []string `protobuf:"bytes,5,rep,name=Conditions,proto3" json:"Conditions,omitempty"`
	StdOut        string   `protobuf:"bytes,6,opt,name=StdOut,proto3" json:"StdOut,omitempty"`
	StdErr        string   `protobuf:"bytes,7,opt,name=StdErr,proto3" json:"StdErr,omitempty"`
	DateCondition string   `protobuf:"bytes,8,opt,name=DateCondition,proto3" json:"DateCondition,omitempty"`
	AlarmIfFail   string   `protobuf:"bytes,9,opt,name=AlarmIfFail,proto3" json:"AlarmIfFail,omitempty"`
	MaxRunAlarm   string   `protobuf:"bytes,10,opt,name=MaxRunAlarm,proto3" json:"MaxRunAlarm,omitempty"`
	Machine       string   `protobuf:"bytes,11,opt,name=Machine,proto3" json:"Machine,omitempty"`
	RunDays       string   `protobuf:"bytes,12,opt,name=RunDays,proto3" json:"RunDays,omitempty"`
	StartTimes    string   `protobuf:"bytes,13,opt,name=StartTimes,proto3" json:"StartTimes,omitempty"`
}

func (x *JilData) Reset() {
	*x = JilData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jil_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JilData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JilData) ProtoMessage() {}

func (x *JilData) ProtoReflect() protoreflect.Message {
	mi := &file_jil_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JilData.ProtoReflect.Descriptor instead.
func (*JilData) Descriptor() ([]byte, []int) {
	return file_jil_proto_rawDescGZIP(), []int{0}
}

func (x *JilData) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JilData) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JilData) GetBoxName() string {
	if x != nil {
		return x.BoxName
	}
	return ""
}

func (x *JilData) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JilData) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *JilData) GetStdOut() string {
	if x != nil {
		return x.StdOut
	}
	return ""
}

func (x *JilData) GetStdErr() string {
	if x != nil {
		return x.StdErr
	}
	return ""
}

func (x *JilData) GetDateCondition() string {
	if x != nil {
		return x.DateCondition
	}
	return ""
}

func (x *JilData) GetAlarmIfFail() string {
	if x != nil {
		return x.AlarmIfFail
	}
	return ""
}

func (x *JilData) GetMaxRunAlarm() string {
	if x != nil {
		return x.MaxRunAlarm
	}
	return ""
}

func (x *JilData) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *JilData) GetRunDays() string {
	if x != nil {
		return x.RunDays
	}
	return ""
}

func (x *JilData) GetStartTimes() string {
	if x != nil {
		return x.StartTimes
	}
	return ""
}

// Message to represent a JIL
type Jil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action        JilAction `protobuf:"varint,1,opt,name=Action,proto3,enum=data.JilAction" json:"Action,omitempty"`
	Data          *JilData  `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	AttributeFlag int32     `protobuf:"varint,3,opt,name=AttributeFlag,proto3" json:"AttributeFlag,omitempty"`
}

func (x *Jil) Reset() {
	*x = Jil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jil_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jil) ProtoMessage() {}

func (x *Jil) ProtoReflect() protoreflect.Message {
	mi := &file_jil_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jil.ProtoReflect.Descriptor instead.
func (*Jil) Descriptor() ([]byte, []int) {
	return file_jil_proto_rawDescGZIP(), []int{1}
}

func (x *Jil) GetAction() JilAction {
	if x != nil {
		return x.Action
	}
	return JilAction_INSERT
}

func (x *Jil) GetData() *JilData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Jil) GetAttributeFlag() int32 {
	if x != nil {
		return x.AttributeFlag
	}
	return 0
}

// Request message to submit JIL data
type SubmitJilReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jil []*Jil `protobuf:"bytes,1,rep,name=Jil,proto3" json:"Jil,omitempty"`
}

func (x *SubmitJilReq) Reset() {
	*x = SubmitJilReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jil_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitJilReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJilReq) ProtoMessage() {}

func (x *SubmitJilReq) ProtoReflect() protoreflect.Message {
	mi := &file_jil_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJilReq.ProtoReflect.Descriptor instead.
func (*SubmitJilReq) Descriptor() ([]byte, []int) {
	return file_jil_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJilReq) GetJil() []*Jil {
	if x != nil {
		return x.Jil
	}
	return nil
}

// Response message for submitted JIL data
type SubmitJilRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created int32 `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated int32 `protobuf:"varint,2,opt,name=Updated,proto3" json:"Updated,omitempty"`
	Deleted int32 `protobuf:"varint,3,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
}

func (x *SubmitJilRes) Reset() {
	*x = SubmitJilRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jil_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitJilRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJilRes) ProtoMessage() {}

func (x *SubmitJilRes) ProtoReflect() protoreflect.Message {
	mi := &file_jil_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJilRes.ProtoReflect.Descriptor instead.
func (*SubmitJilRes) Descriptor() ([]byte, []int) {
	return file_jil_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJilRes) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *SubmitJilRes) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *SubmitJilRes) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_jil_proto protoreflect.FileDescriptor

var file_jil_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6a, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xff, 0x02, 0x0a, 0x07, 0x4a, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6f, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x42, 0x6f, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x4f, 0x75, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x64, 0x45, 0x72, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x74, 0x64, 0x45, 0x72, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x49, 0x66, 0x46, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x49, 0x66, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x4d, 0x61, 0x78, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4d, 0x61, 0x78, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x44, 0x61, 0x79, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x44,
	0x61, 0x79, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x22, 0x77, 0x0a, 0x03, 0x4a, 0x69, 0x6c, 0x12, 0x27, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x4a, 0x69, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4a, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x2b, 0x0a, 0x0c,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x03,
	0x4a, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4a, 0x69, 0x6c, 0x52, 0x03, 0x4a, 0x69, 0x6c, 0x22, 0x5c, 0x0a, 0x0c, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2a, 0x2f, 0x0a, 0x09, 0x4a, 0x69, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x32, 0x3f, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4a, 0x69, 0x6c, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12,
	0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x4a, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jil_proto_rawDescOnce sync.Once
	file_jil_proto_rawDescData = file_jil_proto_rawDesc
)

func file_jil_proto_rawDescGZIP() []byte {
	file_jil_proto_rawDescOnce.Do(func() {
		file_jil_proto_rawDescData = protoimpl.X.CompressGZIP(file_jil_proto_rawDescData)
	})
	return file_jil_proto_rawDescData
}

var file_jil_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jil_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jil_proto_goTypes = []interface{}{
	(JilAction)(0),       // 0: data.JilAction
	(*JilData)(nil),      // 1: data.JilData
	(*Jil)(nil),          // 2: data.Jil
	(*SubmitJilReq)(nil), // 3: data.SubmitJilReq
	(*SubmitJilRes)(nil), // 4: data.SubmitJilRes
}
var file_jil_proto_depIdxs = []int32{
	0, // 0: data.Jil.Action:type_name -> data.JilAction
	1, // 1: data.Jil.Data:type_name -> data.JilData
	2, // 2: data.SubmitJilReq.Jil:type_name -> data.Jil
	3, // 3: data.SubmitJil.Submit:input_type -> data.SubmitJilReq
	4, // 4: data.SubmitJil.Submit:output_type -> data.SubmitJilRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jil_proto_init() }
func file_jil_proto_init() {
	if File_jil_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jil_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JilData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jil_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jil_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitJilReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jil_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitJilRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jil_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jil_proto_goTypes,
		DependencyIndexes: file_jil_proto_depIdxs,
		EnumInfos:         file_jil_proto_enumTypes,
		MessageInfos:      file_jil_proto_msgTypes,
	}.Build()
	File_jil_proto = out.File
	file_jil_proto_rawDesc = nil
	file_jil_proto_goTypes = nil
	file_jil_proto_depIdxs = nil
}
