// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: awake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message to awake waiting dependent tasks for execution
type DependentTaskAwakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64 `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *DependentTaskAwakeRequest) Reset() {
	*x = DependentTaskAwakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_awake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependentTaskAwakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentTaskAwakeRequest) ProtoMessage() {}

func (x *DependentTaskAwakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentTaskAwakeRequest.ProtoReflect.Descriptor instead.
func (*DependentTaskAwakeRequest) Descriptor() ([]byte, []int) {
	return file_awake_proto_rawDescGZIP(), []int{0}
}

func (x *DependentTaskAwakeRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// Response message of awake waiting dependent tasks
type DependentTaskAwakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DependentTaskAwakeResponse) Reset() {
	*x = DependentTaskAwakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_awake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependentTaskAwakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentTaskAwakeResponse) ProtoMessage() {}

func (x *DependentTaskAwakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentTaskAwakeResponse.ProtoReflect.Descriptor instead.
func (*DependentTaskAwakeResponse) Descriptor() ([]byte, []int) {
	return file_awake_proto_rawDescGZIP(), []int{1}
}

var File_awake_proto protoreflect.FileDescriptor

var file_awake_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x77, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x19, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x77, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x77, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x61, 0x0a, 0x0f, 0x57, 0x61, 0x69, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x05, 0x41, 0x77,
	0x61, 0x6b, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x77, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x77, 0x61, 0x6b, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x72, 0x75, 0x6e, 0x2f,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_awake_proto_rawDescOnce sync.Once
	file_awake_proto_rawDescData = file_awake_proto_rawDesc
)

func file_awake_proto_rawDescGZIP() []byte {
	file_awake_proto_rawDescOnce.Do(func() {
		file_awake_proto_rawDescData = protoimpl.X.CompressGZIP(file_awake_proto_rawDescData)
	})
	return file_awake_proto_rawDescData
}

var file_awake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_awake_proto_goTypes = []interface{}{
	(*DependentTaskAwakeRequest)(nil),  // 0: proto.DependentTaskAwakeRequest
	(*DependentTaskAwakeResponse)(nil), // 1: proto.DependentTaskAwakeResponse
}
var file_awake_proto_depIdxs = []int32{
	0, // 0: proto.WaitTaskService.Awake:input_type -> proto.DependentTaskAwakeRequest
	1, // 1: proto.WaitTaskService.Awake:output_type -> proto.DependentTaskAwakeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_awake_proto_init() }
func file_awake_proto_init() {
	if File_awake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_awake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependentTaskAwakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_awake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependentTaskAwakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_awake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_awake_proto_goTypes,
		DependencyIndexes: file_awake_proto_depIdxs,
		MessageInfos:      file_awake_proto_msgTypes,
	}.Build()
	File_awake_proto = out.File
	file_awake_proto_rawDesc = nil
	file_awake_proto_goTypes = nil
	file_awake_proto_depIdxs = nil
}
