// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: callback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_SUCCESS TaskStatus = 0
	TaskStatus_FAILURE TaskStatus = 1
	TaskStatus_ABORTED TaskStatus = 2
	TaskStatus_RUNNING TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "ABORTED",
		3: "RUNNING",
	}
	TaskStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
		"ABORTED": 2,
		"RUNNING": 3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_callback_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{0}
}

// Request message to pull ready tasks for execution
type ReadyTasksPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadyTasksPullRequest) Reset() {
	*x = ReadyTasksPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyTasksPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyTasksPullRequest) ProtoMessage() {}

func (x *ReadyTasksPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyTasksPullRequest.ProtoReflect.Descriptor instead.
func (*ReadyTasksPullRequest) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{0}
}

// Response message contains ready tasks for execution
type ReadyTasksPullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskIds []int64 `protobuf:"varint,1,rep,packed,name=TaskIds,proto3" json:"TaskIds,omitempty"`
}

func (x *ReadyTasksPullResponse) Reset() {
	*x = ReadyTasksPullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyTasksPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyTasksPullResponse) ProtoMessage() {}

func (x *ReadyTasksPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyTasksPullResponse.ProtoReflect.Descriptor instead.
func (*ReadyTasksPullResponse) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyTasksPullResponse) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

// Request message of parsed actions
type TaskInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64 `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *TaskInfoRequest) Reset() {
	*x = TaskInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoRequest) ProtoMessage() {}

func (x *TaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoRequest.ProtoReflect.Descriptor instead.
func (*TaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInfoRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// Response for validated list of jobs
type TaskInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     int64  `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	Command    string `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	OutLogFile string `protobuf:"bytes,3,opt,name=OutLogFile,proto3" json:"OutLogFile,omitempty"`
	ErrLogFile string `protobuf:"bytes,4,opt,name=ErrLogFile,proto3" json:"ErrLogFile,omitempty"`
}

func (x *TaskInfoResponse) Reset() {
	*x = TaskInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoResponse) ProtoMessage() {}

func (x *TaskInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoResponse.ProtoReflect.Descriptor instead.
func (*TaskInfoResponse) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{3}
}

func (x *TaskInfoResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskInfoResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskInfoResponse) GetOutLogFile() string {
	if x != nil {
		return x.OutLogFile
	}
	return ""
}

func (x *TaskInfoResponse) GetErrLogFile() string {
	if x != nil {
		return x.ErrLogFile
	}
	return ""
}

// Request message to set task status
type TaskStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64      `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	Status TaskStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=proto.TaskStatus" json:"Status,omitempty"`
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatusRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_SUCCESS
}

// Response message for task status update
type TaskStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callback_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{5}
}

var File_callback_proto protoreflect.FileDescriptor

var file_callback_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x32, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x50, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x84, 0x01, 0x0a, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x75, 0x74, 0x4c,
	0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x4c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x72, 0x72, 0x4c,
	0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x56, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x14,
	0x0a, 0x12, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x40, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x32, 0xe8, 0x01, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x45,
	0x78, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x50, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x50,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x50, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6c, 0x61, 0x72, 0x75, 0x6e, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_callback_proto_rawDescOnce sync.Once
	file_callback_proto_rawDescData = file_callback_proto_rawDesc
)

func file_callback_proto_rawDescGZIP() []byte {
	file_callback_proto_rawDescOnce.Do(func() {
		file_callback_proto_rawDescData = protoimpl.X.CompressGZIP(file_callback_proto_rawDescData)
	})
	return file_callback_proto_rawDescData
}

var file_callback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_callback_proto_goTypes = []interface{}{
	(TaskStatus)(0),                // 0: proto.TaskStatus
	(*ReadyTasksPullRequest)(nil),  // 1: proto.ReadyTasksPullRequest
	(*ReadyTasksPullResponse)(nil), // 2: proto.ReadyTasksPullResponse
	(*TaskInfoRequest)(nil),        // 3: proto.TaskInfoRequest
	(*TaskInfoResponse)(nil),       // 4: proto.TaskInfoResponse
	(*TaskStatusRequest)(nil),      // 5: proto.TaskStatusRequest
	(*TaskStatusResponse)(nil),     // 6: proto.TaskStatusResponse
}
var file_callback_proto_depIdxs = []int32{
	0, // 0: proto.TaskStatusRequest.Status:type_name -> proto.TaskStatus
	1, // 1: proto.TaskExecService.PullReadyTasks:input_type -> proto.ReadyTasksPullRequest
	3, // 2: proto.TaskExecService.GetTask:input_type -> proto.TaskInfoRequest
	5, // 3: proto.TaskExecService.SetTaskStatus:input_type -> proto.TaskStatusRequest
	2, // 4: proto.TaskExecService.PullReadyTasks:output_type -> proto.ReadyTasksPullResponse
	4, // 5: proto.TaskExecService.GetTask:output_type -> proto.TaskInfoResponse
	6, // 6: proto.TaskExecService.SetTaskStatus:output_type -> proto.TaskStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_callback_proto_init() }
func file_callback_proto_init() {
	if File_callback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_callback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyTasksPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyTasksPullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callback_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_callback_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callback_proto_goTypes,
		DependencyIndexes: file_callback_proto_depIdxs,
		EnumInfos:         file_callback_proto_enumTypes,
		MessageInfos:      file_callback_proto_msgTypes,
	}.Build()
	File_callback_proto = out.File
	file_callback_proto_rawDesc = nil
	file_callback_proto_goTypes = nil
	file_callback_proto_depIdxs = nil
}
