// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: entity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParsedActionServiceClient is the client API for ParsedActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParsedActionServiceClient interface {
	// Submit sends the parsed entities to eventserver
	Submit(ctx context.Context, in *ParsedEntitiesRequest, opts ...grpc.CallOption) (*EntityActionResponse, error)
}

type parsedActionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParsedActionServiceClient(cc grpc.ClientConnInterface) ParsedActionServiceClient {
	return &parsedActionServiceClient{cc}
}

func (c *parsedActionServiceClient) Submit(ctx context.Context, in *ParsedEntitiesRequest, opts ...grpc.CallOption) (*EntityActionResponse, error) {
	out := new(EntityActionResponse)
	err := c.cc.Invoke(ctx, "/proto.ParsedActionService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParsedActionServiceServer is the server API for ParsedActionService service.
// All implementations must embed UnimplementedParsedActionServiceServer
// for forward compatibility
type ParsedActionServiceServer interface {
	// Submit sends the parsed entities to eventserver
	Submit(context.Context, *ParsedEntitiesRequest) (*EntityActionResponse, error)
	mustEmbedUnimplementedParsedActionServiceServer()
}

// UnimplementedParsedActionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedParsedActionServiceServer struct {
}

func (UnimplementedParsedActionServiceServer) Submit(context.Context, *ParsedEntitiesRequest) (*EntityActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedParsedActionServiceServer) mustEmbedUnimplementedParsedActionServiceServer() {}

// UnsafeParsedActionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParsedActionServiceServer will
// result in compilation errors.
type UnsafeParsedActionServiceServer interface {
	mustEmbedUnimplementedParsedActionServiceServer()
}

func RegisterParsedActionServiceServer(s grpc.ServiceRegistrar, srv ParsedActionServiceServer) {
	s.RegisterService(&ParsedActionService_ServiceDesc, srv)
}

func _ParsedActionService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParsedEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsedActionServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ParsedActionService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsedActionServiceServer).Submit(ctx, req.(*ParsedEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParsedActionService_ServiceDesc is the grpc.ServiceDesc for ParsedActionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParsedActionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ParsedActionService",
	HandlerType: (*ParsedActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _ParsedActionService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entity.proto",
}

// ValidatedActionServiceClient is the client API for ValidatedActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidatedActionServiceClient interface {
	// Route sends the parsed entities from client to validator
	Route(ctx context.Context, in *ParsedEntitiesRequest, opts ...grpc.CallOption) (*ValidatedEntitiesResponse, error)
}

type validatedActionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatedActionServiceClient(cc grpc.ClientConnInterface) ValidatedActionServiceClient {
	return &validatedActionServiceClient{cc}
}

func (c *validatedActionServiceClient) Route(ctx context.Context, in *ParsedEntitiesRequest, opts ...grpc.CallOption) (*ValidatedEntitiesResponse, error) {
	out := new(ValidatedEntitiesResponse)
	err := c.cc.Invoke(ctx, "/proto.ValidatedActionService/Route", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatedActionServiceServer is the server API for ValidatedActionService service.
// All implementations must embed UnimplementedValidatedActionServiceServer
// for forward compatibility
type ValidatedActionServiceServer interface {
	// Route sends the parsed entities from client to validator
	Route(context.Context, *ParsedEntitiesRequest) (*ValidatedEntitiesResponse, error)
	mustEmbedUnimplementedValidatedActionServiceServer()
}

// UnimplementedValidatedActionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedValidatedActionServiceServer struct {
}

func (UnimplementedValidatedActionServiceServer) Route(context.Context, *ParsedEntitiesRequest) (*ValidatedEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedValidatedActionServiceServer) mustEmbedUnimplementedValidatedActionServiceServer() {
}

// UnsafeValidatedActionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatedActionServiceServer will
// result in compilation errors.
type UnsafeValidatedActionServiceServer interface {
	mustEmbedUnimplementedValidatedActionServiceServer()
}

func RegisterValidatedActionServiceServer(s grpc.ServiceRegistrar, srv ValidatedActionServiceServer) {
	s.RegisterService(&ValidatedActionService_ServiceDesc, srv)
}

func _ValidatedActionService_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParsedEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatedActionServiceServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValidatedActionService/Route",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatedActionServiceServer).Route(ctx, req.(*ParsedEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidatedActionService_ServiceDesc is the grpc.ServiceDesc for ValidatedActionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidatedActionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ValidatedActionService",
	HandlerType: (*ValidatedActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _ValidatedActionService_Route_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entity.proto",
}
