// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: entity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullableFlag int32

const (
	NullableFlag_NotAvailable NullableFlag = 0
	NullableFlag_Empty        NullableFlag = 1
	NullableFlag_Available    NullableFlag = 2
)

// Enum value maps for NullableFlag.
var (
	NullableFlag_name = map[int32]string{
		0: "NotAvailable",
		1: "Empty",
		2: "Available",
	}
	NullableFlag_value = map[string]int32{
		"NotAvailable": 0,
		"Empty":        1,
		"Available":    2,
	}
)

func (x NullableFlag) Enum() *NullableFlag {
	p := new(NullableFlag)
	*p = x
	return p
}

func (x NullableFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullableFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_proto_enumTypes[0].Descriptor()
}

func (NullableFlag) Type() protoreflect.EnumType {
	return &file_entity_proto_enumTypes[0]
}

func (x NullableFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullableFlag.Descriptor instead.
func (NullableFlag) EnumDescriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

// Request message of parsed actions
type ParsedEntitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks        []*ParsedTaskEntity `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	OnlyValidate bool                `protobuf:"varint,2,opt,name=OnlyValidate,proto3" json:"OnlyValidate,omitempty"`
}

func (x *ParsedEntitiesRequest) Reset() {
	*x = ParsedEntitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedEntitiesRequest) ProtoMessage() {}

func (x *ParsedEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ParsedEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedEntitiesRequest) GetTasks() []*ParsedTaskEntity {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ParsedEntitiesRequest) GetOnlyValidate() bool {
	if x != nil {
		return x.OnlyValidate
	}
	return false
}

// Response for validated list of jobs
type ValidatedEntitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks  []*ValidatedTaskEntity `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	Status *ActionStatus          `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *ValidatedEntitiesResponse) Reset() {
	*x = ValidatedEntitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatedEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedEntitiesResponse) ProtoMessage() {}

func (x *ValidatedEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ValidatedEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatedEntitiesResponse) GetTasks() []*ValidatedTaskEntity {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ValidatedEntitiesResponse) GetStatus() *ActionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Response message of entity action
type EntityActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ActionStatus `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *EntityActionResponse) Reset() {
	*x = EntityActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityActionResponse) ProtoMessage() {}

func (x *EntityActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityActionResponse.ProtoReflect.Descriptor instead.
func (*EntityActionResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{2}
}

func (x *EntityActionResponse) GetStatus() *ActionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ActionStatus represents status of actions
// Iff all actions are implemented successfully then Success will be true
type ActionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Errors   []string `protobuf:"bytes,2,rep,name=Errors,proto3" json:"Errors,omitempty"`
	Warnings []string `protobuf:"bytes,3,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
}

func (x *ActionStatus) Reset() {
	*x = ActionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatus) ProtoMessage() {}

func (x *ActionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatus.ProtoReflect.Descriptor instead.
func (*ActionStatus) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{3}
}

func (x *ActionStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionStatus) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ActionStatus) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// ParsedTaskEntity represents the task entity with its fields for validation
type ParsedTaskEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string            `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Target string            `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	Fields map[string]string `protobuf:"bytes,3,rep,name=Fields,proto3" json:"Fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ParsedTaskEntity) Reset() {
	*x = ParsedTaskEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedTaskEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTaskEntity) ProtoMessage() {}

func (x *ParsedTaskEntity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTaskEntity.ProtoReflect.Descriptor instead.
func (*ParsedTaskEntity) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{4}
}

func (x *ParsedTaskEntity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ParsedTaskEntity) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ParsedTaskEntity) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ValidatedTaskEntity represents validated job data
type ValidatedTaskEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     string             `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Name       string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type       *NullableString    `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Parent     *NullableString    `protobuf:"bytes,4,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Machine    *NullableString    `protobuf:"bytes,5,opt,name=Machine,proto3" json:"Machine,omitempty"`
	Command    *NullableString    `protobuf:"bytes,6,opt,name=Command,proto3" json:"Command,omitempty"`
	Condition  *NullableString    `protobuf:"bytes,7,opt,name=Condition,proto3" json:"Condition,omitempty"`
	OutLogFile *NullableString    `protobuf:"bytes,8,opt,name=OutLogFile,proto3" json:"OutLogFile,omitempty"`
	ErrLogFile *NullableString    `protobuf:"bytes,9,opt,name=ErrLogFile,proto3" json:"ErrLogFile,omitempty"`
	Label      *NullableString    `protobuf:"bytes,10,opt,name=Label,proto3" json:"Label,omitempty"`
	Profile    *NullableString    `protobuf:"bytes,11,opt,name=Profile,proto3" json:"Profile,omitempty"`
	RunDays    *NullableInt32     `protobuf:"bytes,12,opt,name=RunDays,proto3" json:"RunDays,omitempty"`
	StartTimes *NullableStrings   `protobuf:"bytes,13,opt,name=StartTimes,proto3" json:"StartTimes,omitempty"`
	RunWindow  *NullableTimeRange `protobuf:"bytes,14,opt,name=RunWindow,proto3" json:"RunWindow,omitempty"`
	StartMins  *NullableInt32S    `protobuf:"bytes,15,opt,name=StartMins,proto3" json:"StartMins,omitempty"`
	Priority   *NullableInt32     `protobuf:"bytes,16,opt,name=Priority,proto3" json:"Priority,omitempty"`
}

func (x *ValidatedTaskEntity) Reset() {
	*x = ValidatedTaskEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatedTaskEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedTaskEntity) ProtoMessage() {}

func (x *ValidatedTaskEntity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedTaskEntity.ProtoReflect.Descriptor instead.
func (*ValidatedTaskEntity) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatedTaskEntity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ValidatedTaskEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidatedTaskEntity) GetType() *NullableString {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ValidatedTaskEntity) GetParent() *NullableString {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ValidatedTaskEntity) GetMachine() *NullableString {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *ValidatedTaskEntity) GetCommand() *NullableString {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ValidatedTaskEntity) GetCondition() *NullableString {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *ValidatedTaskEntity) GetOutLogFile() *NullableString {
	if x != nil {
		return x.OutLogFile
	}
	return nil
}

func (x *ValidatedTaskEntity) GetErrLogFile() *NullableString {
	if x != nil {
		return x.ErrLogFile
	}
	return nil
}

func (x *ValidatedTaskEntity) GetLabel() *NullableString {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *ValidatedTaskEntity) GetProfile() *NullableString {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ValidatedTaskEntity) GetRunDays() *NullableInt32 {
	if x != nil {
		return x.RunDays
	}
	return nil
}

func (x *ValidatedTaskEntity) GetStartTimes() *NullableStrings {
	if x != nil {
		return x.StartTimes
	}
	return nil
}

func (x *ValidatedTaskEntity) GetRunWindow() *NullableTimeRange {
	if x != nil {
		return x.RunWindow
	}
	return nil
}

func (x *ValidatedTaskEntity) GetStartMins() *NullableInt32S {
	if x != nil {
		return x.StartMins
	}
	return nil
}

func (x *ValidatedTaskEntity) GetPriority() *NullableInt32 {
	if x != nil {
		return x.Priority
	}
	return nil
}

// Request message to get task definition
type TaskDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
}

func (x *TaskDefinitionRequest) Reset() {
	*x = TaskDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinitionRequest) ProtoMessage() {}

func (x *TaskDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinitionRequest.ProtoReflect.Descriptor instead.
func (*TaskDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{6}
}

func (x *TaskDefinitionRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

type TaskDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool            `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	Task    *TaskDefinition `protobuf:"bytes,2,opt,name=Task,proto3" json:"Task,omitempty"`
}

func (x *TaskDefinitionResponse) Reset() {
	*x = TaskDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinitionResponse) ProtoMessage() {}

func (x *TaskDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinitionResponse.ProtoReflect.Descriptor instead.
func (*TaskDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{7}
}

func (x *TaskDefinitionResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TaskDefinitionResponse) GetTask() *TaskDefinition {
	if x != nil {
		return x.Task
	}
	return nil
}

// Response message of task definition
type TaskDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Params        map[string]string `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ChildrenTasks []*TaskDefinition `protobuf:"bytes,3,rep,name=ChildrenTasks,proto3" json:"ChildrenTasks,omitempty"`
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{8}
}

func (x *TaskDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDefinition) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TaskDefinition) GetChildrenTasks() []*TaskDefinition {
	if x != nil {
		return x.ChildrenTasks
	}
	return nil
}

// Request message to get task status
type TaskLatestStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
}

func (x *TaskLatestStatusRequest) Reset() {
	*x = TaskLatestStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskLatestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLatestStatusRequest) ProtoMessage() {}

func (x *TaskLatestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLatestStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskLatestStatusRequest) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{9}
}

func (x *TaskLatestStatusRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

// Response message of task status
type TaskLatestStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool           `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	Status  *TaskRunStatus `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *TaskLatestStatusResponse) Reset() {
	*x = TaskLatestStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskLatestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLatestStatusResponse) ProtoMessage() {}

func (x *TaskLatestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLatestStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskLatestStatusResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{10}
}

func (x *TaskLatestStatusResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TaskLatestStatusResponse) GetStatus() *TaskRunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TaskRunStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName      string           `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	LastStartTime string           `protobuf:"bytes,2,opt,name=LastStartTime,proto3" json:"LastStartTime,omitempty"`
	LastEndTime   string           `protobuf:"bytes,3,opt,name=LastEndTime,proto3" json:"LastEndTime,omitempty"`
	Status        string           `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Children      []*TaskRunStatus `protobuf:"bytes,5,rep,name=Children,proto3" json:"Children,omitempty"`
}

func (x *TaskRunStatus) Reset() {
	*x = TaskRunStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRunStatus) ProtoMessage() {}

func (x *TaskRunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRunStatus.ProtoReflect.Descriptor instead.
func (*TaskRunStatus) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{11}
}

func (x *TaskRunStatus) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskRunStatus) GetLastStartTime() string {
	if x != nil {
		return x.LastStartTime
	}
	return ""
}

func (x *TaskRunStatus) GetLastEndTime() string {
	if x != nil {
		return x.LastEndTime
	}
	return ""
}

func (x *TaskRunStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskRunStatus) GetChildren() []*TaskRunStatus {
	if x != nil {
		return x.Children
	}
	return nil
}

// Request message to get last n runs of task
type TaskRunsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	RunDate  string `protobuf:"bytes,3,opt,name=RunDate,proto3" json:"RunDate,omitempty"`
}

func (x *TaskRunsRequest) Reset() {
	*x = TaskRunsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRunsRequest) ProtoMessage() {}

func (x *TaskRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRunsRequest.ProtoReflect.Descriptor instead.
func (*TaskRunsRequest) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{12}
}

func (x *TaskRunsRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskRunsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TaskRunsRequest) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

// Response message of last n runs of task
type TaskRunsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool             `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	Runs    []*TaskRunStatus `protobuf:"bytes,2,rep,name=Runs,proto3" json:"Runs,omitempty"`
}

func (x *TaskRunsResponse) Reset() {
	*x = TaskRunsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRunsResponse) ProtoMessage() {}

func (x *TaskRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRunsResponse.ProtoReflect.Descriptor instead.
func (*TaskRunsResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{13}
}

func (x *TaskRunsResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TaskRunsResponse) GetRuns() []*TaskRunStatus {
	if x != nil {
		return x.Runs
	}
	return nil
}

type NullableString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string       `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Flag  NullableFlag `protobuf:"varint,2,opt,name=flag,proto3,enum=proto.NullableFlag" json:"flag,omitempty"`
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{14}
}

func (x *NullableString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NullableString) GetFlag() NullableFlag {
	if x != nil {
		return x.Flag
	}
	return NullableFlag_NotAvailable
}

type NullableStrings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string     `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	Flag  NullableFlag `protobuf:"varint,2,opt,name=flag,proto3,enum=proto.NullableFlag" json:"flag,omitempty"`
}

func (x *NullableStrings) Reset() {
	*x = NullableStrings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableStrings) ProtoMessage() {}

func (x *NullableStrings) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableStrings.ProtoReflect.Descriptor instead.
func (*NullableStrings) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{15}
}

func (x *NullableStrings) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NullableStrings) GetFlag() NullableFlag {
	if x != nil {
		return x.Flag
	}
	return NullableFlag_NotAvailable
}

type NullableInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32        `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Flag  NullableFlag `protobuf:"varint,2,opt,name=flag,proto3,enum=proto.NullableFlag" json:"flag,omitempty"`
}

func (x *NullableInt32) Reset() {
	*x = NullableInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableInt32) ProtoMessage() {}

func (x *NullableInt32) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableInt32.ProtoReflect.Descriptor instead.
func (*NullableInt32) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{16}
}

func (x *NullableInt32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NullableInt32) GetFlag() NullableFlag {
	if x != nil {
		return x.Flag
	}
	return NullableFlag_NotAvailable
}

type NullableInt32S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []int32      `protobuf:"varint,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
	Flag  NullableFlag `protobuf:"varint,2,opt,name=flag,proto3,enum=proto.NullableFlag" json:"flag,omitempty"`
}

func (x *NullableInt32S) Reset() {
	*x = NullableInt32S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableInt32S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableInt32S) ProtoMessage() {}

func (x *NullableInt32S) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableInt32S.ProtoReflect.Descriptor instead.
func (*NullableInt32S) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{17}
}

func (x *NullableInt32S) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NullableInt32S) GetFlag() NullableFlag {
	if x != nil {
		return x.Flag
	}
	return NullableFlag_NotAvailable
}

type TimeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=Start,proto3" json:"Start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=End,proto3" json:"End,omitempty"`
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{18}
}

func (x *TimeRange) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type NullableTimeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *TimeRange   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Flag  NullableFlag `protobuf:"varint,2,opt,name=flag,proto3,enum=proto.NullableFlag" json:"flag,omitempty"`
}

func (x *NullableTimeRange) Reset() {
	*x = NullableTimeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableTimeRange) ProtoMessage() {}

func (x *NullableTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableTimeRange.ProtoReflect.Descriptor instead.
func (*NullableTimeRange) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{19}
}

func (x *NullableTimeRange) GetValue() *TimeRange {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NullableTimeRange) GetFlag() NullableFlag {
	if x != nil {
		return x.Flag
	}
	return NullableFlag_NotAvailable
}

var File_entity_proto protoreflect.FileDescriptor

var file_entity_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x15, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x22, 0x0a,
	0x0c, 0x4f, 0x6e, 0x6c, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x4f, 0x6e, 0x6c, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x7a, 0x0a, 0x19, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a,
	0x14, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x5c, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0xba, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x85, 0x06,
	0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x06,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x2f, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x33, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x4f,
	0x75, 0x74, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x45, 0x72, 0x72,
	0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x45, 0x72, 0x72, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x2b, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x2f, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2e,
	0x0a, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x36,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x52, 0x75, 0x6e, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x09, 0x52, 0x75, 0x6e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x33,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6e, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d,
	0x69, 0x6e, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x08, 0x50, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x33, 0x0a, 0x15, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x16, 0x54, 0x61,
	0x73, 0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x29,
	0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x22, 0xd7, 0x01, 0x0a, 0x0e, 0x54, 0x61,
	0x73, 0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x39, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x43,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x43, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x17, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x18, 0x54, 0x61,
	0x73, 0x6b, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x12, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbd,
	0x01, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x4c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x08,
	0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x5d,
	0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x56, 0x0a,
	0x10, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x52,
	0x75, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x04, 0x52, 0x75, 0x6e, 0x73, 0x22, 0x4f, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x50, 0x0a, 0x0f, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x27, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4e, 0x0a, 0x0d, 0x4e, 0x75, 0x6c, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x27, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4f, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x27, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x33, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x22, 0x64,
	0x0a, 0x11, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x2a, 0x3a, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x02,
	0x32, 0x5c, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x63,
	0x0a, 0x16, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x32, 0xeb, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x73, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6c, 0x61, 0x72, 0x75, 0x6e, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_proto_rawDescOnce sync.Once
	file_entity_proto_rawDescData = file_entity_proto_rawDesc
)

func file_entity_proto_rawDescGZIP() []byte {
	file_entity_proto_rawDescOnce.Do(func() {
		file_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_proto_rawDescData)
	})
	return file_entity_proto_rawDescData
}

var file_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_entity_proto_goTypes = []interface{}{
	(NullableFlag)(0),                 // 0: proto.NullableFlag
	(*ParsedEntitiesRequest)(nil),     // 1: proto.ParsedEntitiesRequest
	(*ValidatedEntitiesResponse)(nil), // 2: proto.ValidatedEntitiesResponse
	(*EntityActionResponse)(nil),      // 3: proto.EntityActionResponse
	(*ActionStatus)(nil),              // 4: proto.ActionStatus
	(*ParsedTaskEntity)(nil),          // 5: proto.ParsedTaskEntity
	(*ValidatedTaskEntity)(nil),       // 6: proto.ValidatedTaskEntity
	(*TaskDefinitionRequest)(nil),     // 7: proto.TaskDefinitionRequest
	(*TaskDefinitionResponse)(nil),    // 8: proto.TaskDefinitionResponse
	(*TaskDefinition)(nil),            // 9: proto.TaskDefinition
	(*TaskLatestStatusRequest)(nil),   // 10: proto.TaskLatestStatusRequest
	(*TaskLatestStatusResponse)(nil),  // 11: proto.TaskLatestStatusResponse
	(*TaskRunStatus)(nil),             // 12: proto.TaskRunStatus
	(*TaskRunsRequest)(nil),           // 13: proto.TaskRunsRequest
	(*TaskRunsResponse)(nil),          // 14: proto.TaskRunsResponse
	(*NullableString)(nil),            // 15: proto.NullableString
	(*NullableStrings)(nil),           // 16: proto.NullableStrings
	(*NullableInt32)(nil),             // 17: proto.NullableInt32
	(*NullableInt32S)(nil),            // 18: proto.NullableInt32s
	(*TimeRange)(nil),                 // 19: proto.TimeRange
	(*NullableTimeRange)(nil),         // 20: proto.NullableTimeRange
	nil,                               // 21: proto.ParsedTaskEntity.FieldsEntry
	nil,                               // 22: proto.TaskDefinition.ParamsEntry
}
var file_entity_proto_depIdxs = []int32{
	5,  // 0: proto.ParsedEntitiesRequest.Tasks:type_name -> proto.ParsedTaskEntity
	6,  // 1: proto.ValidatedEntitiesResponse.Tasks:type_name -> proto.ValidatedTaskEntity
	4,  // 2: proto.ValidatedEntitiesResponse.Status:type_name -> proto.ActionStatus
	4,  // 3: proto.EntityActionResponse.Status:type_name -> proto.ActionStatus
	21, // 4: proto.ParsedTaskEntity.Fields:type_name -> proto.ParsedTaskEntity.FieldsEntry
	15, // 5: proto.ValidatedTaskEntity.Type:type_name -> proto.NullableString
	15, // 6: proto.ValidatedTaskEntity.Parent:type_name -> proto.NullableString
	15, // 7: proto.ValidatedTaskEntity.Machine:type_name -> proto.NullableString
	15, // 8: proto.ValidatedTaskEntity.Command:type_name -> proto.NullableString
	15, // 9: proto.ValidatedTaskEntity.Condition:type_name -> proto.NullableString
	15, // 10: proto.ValidatedTaskEntity.OutLogFile:type_name -> proto.NullableString
	15, // 11: proto.ValidatedTaskEntity.ErrLogFile:type_name -> proto.NullableString
	15, // 12: proto.ValidatedTaskEntity.Label:type_name -> proto.NullableString
	15, // 13: proto.ValidatedTaskEntity.Profile:type_name -> proto.NullableString
	17, // 14: proto.ValidatedTaskEntity.RunDays:type_name -> proto.NullableInt32
	16, // 15: proto.ValidatedTaskEntity.StartTimes:type_name -> proto.NullableStrings
	20, // 16: proto.ValidatedTaskEntity.RunWindow:type_name -> proto.NullableTimeRange
	18, // 17: proto.ValidatedTaskEntity.StartMins:type_name -> proto.NullableInt32s
	17, // 18: proto.ValidatedTaskEntity.Priority:type_name -> proto.NullableInt32
	9,  // 19: proto.TaskDefinitionResponse.Task:type_name -> proto.TaskDefinition
	22, // 20: proto.TaskDefinition.Params:type_name -> proto.TaskDefinition.ParamsEntry
	9,  // 21: proto.TaskDefinition.ChildrenTasks:type_name -> proto.TaskDefinition
	12, // 22: proto.TaskLatestStatusResponse.Status:type_name -> proto.TaskRunStatus
	12, // 23: proto.TaskRunStatus.Children:type_name -> proto.TaskRunStatus
	12, // 24: proto.TaskRunsResponse.Runs:type_name -> proto.TaskRunStatus
	0,  // 25: proto.NullableString.flag:type_name -> proto.NullableFlag
	0,  // 26: proto.NullableStrings.flag:type_name -> proto.NullableFlag
	0,  // 27: proto.NullableInt32.flag:type_name -> proto.NullableFlag
	0,  // 28: proto.NullableInt32s.flag:type_name -> proto.NullableFlag
	19, // 29: proto.NullableTimeRange.Value:type_name -> proto.TimeRange
	0,  // 30: proto.NullableTimeRange.flag:type_name -> proto.NullableFlag
	1,  // 31: proto.ParsedActionService.Submit:input_type -> proto.ParsedEntitiesRequest
	1,  // 32: proto.ValidatedActionService.Route:input_type -> proto.ParsedEntitiesRequest
	7,  // 33: proto.TaskService.GetDefinition:input_type -> proto.TaskDefinitionRequest
	10, // 34: proto.TaskService.GetStatus:input_type -> proto.TaskLatestStatusRequest
	13, // 35: proto.TaskService.GetRuns:input_type -> proto.TaskRunsRequest
	3,  // 36: proto.ParsedActionService.Submit:output_type -> proto.EntityActionResponse
	2,  // 37: proto.ValidatedActionService.Route:output_type -> proto.ValidatedEntitiesResponse
	8,  // 38: proto.TaskService.GetDefinition:output_type -> proto.TaskDefinitionResponse
	11, // 39: proto.TaskService.GetStatus:output_type -> proto.TaskLatestStatusResponse
	14, // 40: proto.TaskService.GetRuns:output_type -> proto.TaskRunsResponse
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_entity_proto_init() }
func file_entity_proto_init() {
	if File_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedEntitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatedEntitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedTaskEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatedTaskEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskLatestStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskLatestStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRunStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRunsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRunsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableStrings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableInt32S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableTimeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_entity_proto_goTypes,
		DependencyIndexes: file_entity_proto_depIdxs,
		EnumInfos:         file_entity_proto_enumTypes,
		MessageInfos:      file_entity_proto_msgTypes,
	}.Build()
	File_entity_proto = out.File
	file_entity_proto_rawDesc = nil
	file_entity_proto_goTypes = nil
	file_entity_proto_depIdxs = nil
}
