// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: lock.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message to check if its locked
type CheckLockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *CheckLockReq) Reset() {
	*x = CheckLockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLockReq) ProtoMessage() {}

func (x *CheckLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLockReq.ProtoReflect.Descriptor instead.
func (*CheckLockReq) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLockReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// Response message for lock status of job
type CheckLockRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	Locked  bool   `protobuf:"varint,2,opt,name=Locked,proto3" json:"Locked,omitempty"`
}

func (x *CheckLockRes) Reset() {
	*x = CheckLockRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckLockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLockRes) ProtoMessage() {}

func (x *CheckLockRes) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLockRes.ProtoReflect.Descriptor instead.
func (*CheckLockRes) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLockRes) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CheckLockRes) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

var File_lock_proto protoreflect.FileDescriptor

var file_lock_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x28, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a,
	0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x32, 0x3e,
	0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x31, 0x0a, 0x05, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lock_proto_rawDescOnce sync.Once
	file_lock_proto_rawDescData = file_lock_proto_rawDesc
)

func file_lock_proto_rawDescGZIP() []byte {
	file_lock_proto_rawDescOnce.Do(func() {
		file_lock_proto_rawDescData = protoimpl.X.CompressGZIP(file_lock_proto_rawDescData)
	})
	return file_lock_proto_rawDescData
}

var file_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lock_proto_goTypes = []interface{}{
	(*CheckLockReq)(nil), // 0: data.CheckLockReq
	(*CheckLockRes)(nil), // 1: data.CheckLockRes
}
var file_lock_proto_depIdxs = []int32{
	0, // 0: data.CheckLock.Check:input_type -> data.CheckLockReq
	1, // 1: data.CheckLock.Check:output_type -> data.CheckLockRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lock_proto_init() }
func file_lock_proto_init() {
	if File_lock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckLockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckLockRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lock_proto_goTypes,
		DependencyIndexes: file_lock_proto_depIdxs,
		MessageInfos:      file_lock_proto_msgTypes,
	}.Build()
	File_lock_proto = out.File
	file_lock_proto_rawDesc = nil
	file_lock_proto_goTypes = nil
	file_lock_proto_depIdxs = nil
}
