// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckLockClient is the client API for CheckLock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckLockClient interface {
	Check(ctx context.Context, in *CheckLockReq, opts ...grpc.CallOption) (*CheckLockRes, error)
}

type checkLockClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckLockClient(cc grpc.ClientConnInterface) CheckLockClient {
	return &checkLockClient{cc}
}

func (c *checkLockClient) Check(ctx context.Context, in *CheckLockReq, opts ...grpc.CallOption) (*CheckLockRes, error) {
	out := new(CheckLockRes)
	err := c.cc.Invoke(ctx, "/data.CheckLock/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckLockServer is the server API for CheckLock service.
// All implementations must embed UnimplementedCheckLockServer
// for forward compatibility
type CheckLockServer interface {
	Check(context.Context, *CheckLockReq) (*CheckLockRes, error)
	mustEmbedUnimplementedCheckLockServer()
}

// UnimplementedCheckLockServer must be embedded to have forward compatible implementations.
type UnimplementedCheckLockServer struct {
}

func (UnimplementedCheckLockServer) Check(context.Context, *CheckLockReq) (*CheckLockRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedCheckLockServer) mustEmbedUnimplementedCheckLockServer() {}

// UnsafeCheckLockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckLockServer will
// result in compilation errors.
type UnsafeCheckLockServer interface {
	mustEmbedUnimplementedCheckLockServer()
}

func RegisterCheckLockServer(s grpc.ServiceRegistrar, srv CheckLockServer) {
	s.RegisterService(&CheckLock_ServiceDesc, srv)
}

func _CheckLock_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckLockServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.CheckLock/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckLockServer).Check(ctx, req.(*CheckLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckLock_ServiceDesc is the grpc.ServiceDesc for CheckLock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckLock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.CheckLock",
	HandlerType: (*CheckLockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _CheckLock_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lock.proto",
}
