// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: run.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message to get the run data of job
type RunDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *RunDataReq) Reset() {
	*x = RunDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDataReq) ProtoMessage() {}

func (x *RunDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDataReq.ProtoReflect.Descriptor instead.
func (*RunDataReq) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

func (x *RunDataReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

// Response message for job's run data
type RunDataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	Machine string `protobuf:"bytes,3,opt,name=Machine,proto3" json:"Machine,omitempty"`
	OutFile string `protobuf:"bytes,4,opt,name=OutFile,proto3" json:"OutFile,omitempty"`
	ErrFile string `protobuf:"bytes,5,opt,name=ErrFile,proto3" json:"ErrFile,omitempty"`
}

func (x *RunDataRes) Reset() {
	*x = RunDataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDataRes) ProtoMessage() {}

func (x *RunDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDataRes.ProtoReflect.Descriptor instead.
func (*RunDataRes) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{1}
}

func (x *RunDataRes) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RunDataRes) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunDataRes) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *RunDataRes) GetOutFile() string {
	if x != nil {
		return x.OutFile
	}
	return ""
}

func (x *RunDataRes) GetErrFile() string {
	if x != nil {
		return x.ErrFile
	}
	return ""
}

var File_run_proto protoreflect.FileDescriptor

var file_run_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x26, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x52, 0x75,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x72, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x3d, 0x0a, 0x07, 0x52, 0x75,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x75, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x75, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_run_proto_rawDescOnce sync.Once
	file_run_proto_rawDescData = file_run_proto_rawDesc
)

func file_run_proto_rawDescGZIP() []byte {
	file_run_proto_rawDescOnce.Do(func() {
		file_run_proto_rawDescData = protoimpl.X.CompressGZIP(file_run_proto_rawDescData)
	})
	return file_run_proto_rawDescData
}

var file_run_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_run_proto_goTypes = []interface{}{
	(*RunDataReq)(nil), // 0: data.RunDataReq
	(*RunDataRes)(nil), // 1: data.RunDataRes
}
var file_run_proto_depIdxs = []int32{
	0, // 0: data.RunData.GetRunData:input_type -> data.RunDataReq
	1, // 1: data.RunData.GetRunData:output_type -> data.RunDataRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_run_proto_init() }
func file_run_proto_init() {
	if File_run_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_run_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_run_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunDataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_run_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_run_proto_goTypes,
		DependencyIndexes: file_run_proto_depIdxs,
		MessageInfos:      file_run_proto_msgTypes,
	}.Build()
	File_run_proto = out.File
	file_run_proto_rawDesc = nil
	file_run_proto_goTypes = nil
	file_run_proto_depIdxs = nil
}
